server:
  port: 8082

spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true